// <auto-generated />
namespace Appreciation.Manager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class alter_Student_View_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_Student_View_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201912272313004_alter_Student_View_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
