// <auto-generated />
namespace Appreciation.Manager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_schoolyear_foreign_key_to_exam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_schoolyear_foreign_key_to_exam));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101504280_add_schoolyear_foreign_key_to_exam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
