// <auto-generated />
namespace Appreciation.Manager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class alter_BehaviorEvaluate_view_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_BehaviorEvaluate_view_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001061015402_alter_BehaviorEvaluate_view_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
