// <auto-generated />
namespace Appreciation.Manager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_foreign_key_schoolyear_to_Classroom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_foreign_key_schoolyear_to_Classroom));
        
        string IMigrationMetadata.Id
        {
            get { return "202001090853423_add_foreign_key_schoolyear_to_Classroom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
