// <auto-generated />
namespace Appreciation.Manager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class alter_NoteEvaluate_view_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_NoteEvaluate_view_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001050042283_alter_NoteEvaluate_view_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
