// <auto-generated />
namespace Appreciation.Manager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class update_foreign_key_Exam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_foreign_key_Exam));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101441179_update_foreign_key_Exam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
